# Generated by Django 3.1.7 on 2021-06-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='pictures')),
                ('old_price', models.IntegerField()),
                ('new_price', models.IntegerField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
